#!/bin/bash

battery_capacity() {
    BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
    cat /sys/class/power_supply/${BAT}/capacity
}

battery_stat() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	cat /sys/class/power_supply/${BAT}/status
}

battery_icon() {
    BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
    CAPACITY=$(cat /sys/class/power_supply/${BAT}/capacity)
 
    # check if is charging
    [ $(cat /sys/class/power_supply/${BAT}/status) = "Charging" ] && echo "" && exit

    battery_icons=("󰂃" "󰁺" "󰁻" "󰁼" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹" "󰂄")
    
    capacity_index=$((CAPACITY / 10))
    battery_icon=${battery_icons[capacity_index]}

    echo "${battery_icon}"
}

if [[ "$1" == "--bat" ]]; then
    battery_capacity
elif [[ "$1" == "--bat-status" ]]; then
    battery_stat
elif [[ "$1" == "--bat-icon" ]]; then
    battery_icon
fi
